package net.sharetrip.visa.utils


const val ARG_VISA_BOOKING_CODE = "VISA_BOOKING_CODE"
const val VISA_HISTORY_CANCELLATION = "VisaHistoryCancellationScreen.CONTACT"

const val VISA_PRODUCT_SNAPSHOT = "VISA_PRODUCT_SNAPSHOT"
const val VISA_TRAVELLER_COUNT = "VISA_TRAVELLER_COUNT"
const val VISA_CONVENIENCE_FEE = "VISA_CONVENIENCE_FEE"
const val VISA_VAT_ON_CONVENIENCE_FEE = "VISA_VAT_ON_CONVENIENCE_FEE"

const val VISA_HISTORY_CONTACT = "VisaHistoryContactScreen.CONTACT"

const val VISA_HISTORY_TRAVELLERS = "VISA_HISTORY_TRAVELLERS"

