import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    const val databinding_common: String = "androidx.databinding:databinding-common:_"

    const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:_"

    const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    const val multidex: String = "androidx.multidex:multidex:_"

    const val multidex_instrumentation: String = "androidx.multidex:multidex-instrumentation:_"

    const val paging_runtime: String = "androidx.paging:paging-runtime:_"

    const val recyclerview_selection: String = "androidx.recyclerview:recyclerview-selection:_"

    const val room_compiler: String = "androidx.room:room-compiler:_"

    const val room_ktx: String = "androidx.room:room-ktx:_"

    const val room_runtime: String = "androidx.room:room-runtime:_"

    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_rules: String = "androidx.test:rules:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val lottie: String = "com.airbnb.android:lottie:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val crystalrangeseekbar: String = "com.crystal:crystalrangeseekbar:_"

    const val blurview: String = "com.eightbitlab:blurview:_"

    const val facebook_android_sdk: String = "com.facebook.android:facebook-android-sdk:_"

    const val facebook_marketing: String = "com.facebook.android:facebook-marketing:_"

    const val facebook_login: String = "com.facebook.android:facebook-login:_"

    const val shimmer: String = "com.facebook.shimmer:shimmer:_"

    const val stetho: String = "com.facebook.stetho:stetho:_"

    const val stetho_okhttp3: String = "com.facebook.stetho:stetho-okhttp3:_"

    const val glide: String = "com.github.bumptech.glide:glide:_"
    const val glide_compiler = "com.github.bumptech.glide:compiler:_"
    const val spinnerdatepicker: String = "com.github.drawers:SpinnerDatePicker:_"

    const val calendarview: String = "com.github.kizitonwose:CalendarView:_"

    const val bigimageviewer: String = "com.github.piasy:BigImageViewer:_"

    const val play_services_auth: String = "com.google.android.gms:play-services-auth:_"

    const val play_services_maps: String = "com.google.android.gms:play-services-maps:_"

    const val material: String = "com.google.android.material:material:_"

    const val gson: String = "com.google.code.gson:gson:_"

    const val firebase_analytics: String = "com.google.firebase:firebase-analytics-ktx:_"

    const val firebase_config: String = "com.google.firebase:firebase-config:_"

    const val firebase_core: String = "com.google.firebase:firebase-core:_"

    const val firebase_crashlytics: String = "com.google.firebase:firebase-crashlytics:_"

    const val firebase_crashlytics_gradle: String =
        "com.google.firebase:firebase-crashlytics-gradle:_"

    const val firebase_messaging: String = "com.google.firebase:firebase-messaging:_"

    const val firebase_perf_ktx: String = "com.google.firebase:firebase-perf-ktx:_"

    const val perf_plugin: String = "com.google.firebase:perf-plugin:_"

    const val google_services: String = "com.google.gms:google-services:_"

    const val truth: String = "com.google.truth:truth:_"

    const val timber: String = "com.jakewharton.timber:timber:_"

    const val dexter: String = "com.karumi:dexter:_"

    const val android_saripaar: String = "com.mobsandgeeks:android-saripaar:_"

    const val ink_page_indicator: String = "com.pacioianu.david:ink-page-indicator:_"

    const val leonidslib: String = "com.plattysoft.leonids:LeonidsLib:_"

    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

    const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    const val android_times_square: String = "com.squareup:android-times-square:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
        "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val circleimageview: String = "de.hdodenhof:circleimageview:_"

    const val sectionedrecyclerviewadapter: String =
        "io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:_"

    const val socket_io_client: String = "io.socket:socket.io-client:_"

    const val junit: String = "junit:junit:_"

    const val kotlin_annotation_processing_gradle: String =
        "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_parcelize_compiler: String = "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    const val kotlin_parcelize_runtime: String = "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    const val mockito_core: String = "org.mockito:mockito-core:_"

    const val viewpager2: String = "androidx.viewpager2:viewpager2:_"

    const val work_manager: String = "androidx.work:work-runtime-ktx:_"

    const val crisp_chat: String = "im.crisp:crisp-sdk:_"
}
