package net.sharetrip.bus.utils

const val EXTRA_STATION_NAME = "EXTRA_STATION_NAME"
const val EXTRA_STATION_CODE = "EXTRA_STATION_CODE"
const val ARG_SEARCH_QUERY_HINT = "ARG_SEARCH_QUERY_HINT"

const val ARG_SEARCH_FROM_WHERE = "ARG_SEARCH_FROM_WHERE"
const val ARG_ORIGIN_STATION_CODE = "ARG_ORIGIN_STATION_CODE"

const val PICK_FROM_ADDRESS_REQUEST = "PICK_FROM_ADDRESS_REQUEST"
const val PICK_TO_ADDRESS_REQUEST = "PICK_TO_ADDRESS_REQUEST"

const val BUS_LIST_FILTER_DATA = "BUS_LIST_FILTER_DATA"

//BusListFragment
const val ARG_ORIGIN_CITY = "ARG_ORIGIN_CITY"
const val ARG_DESTINATION_CITY = "ARG_DESTINATION_CITY"
const val ARG_DEPARTURE_DATE = "ARG_DEPARTURE_DATE"
const val ARG_ORIGIN_NAME = "origin_name"
const val ARG_DESTINATION_NAME = "destination_name"